### ISSUE TITLE
Exception while ticking Crash

### ISSUE THREAD

**Issue by Stebbbi** [AugustoResende/VanillaExperience#1]
I have Vanilla Experience installed on my Fabric 1.16.2 server. I only have Zero Tick Unpatch enabled and it seems to have something to do with kelp because the it first crashed when my friend was trying to get some kelp and it kept crashing whenever he joined the server and I had to remove the mod so it wouldn't crash. Then I tested it a bit and I found it crashed when I was placing and breaking kelp.
[crash-2020-09-06_23.23.51-server.txt](https://github.com/AugustoResende/VanillaExperience/files/5180496/crash-2020-09-06_23.23.51-server.txt)

**Comment by Caseyyy93** [comment]
Same for me :(

**Comment by augustresende** [comment]
Fixed.

**Comment by Zarpyk** [comment]
The crash continue in the new version
[crash-2020-10-27_15.45.00-server.txt](https://github.com/AugustoResende/VanillaExperience/files/5446074/crash-2020-10-27_15.45.00-server.txt)
(1.16.3 Fabric Server)

**Comment by augustresende** [comment]
Now is fixed in 0.2.4
