### ISSUE TITLE
Farming problem

### ISSUE THREAD

**Issue by Gomez96** [AugustoResende/VanillaExperience#2]
The game crashes, when I'm trying to approach and collect Kelp, Weeping Vines and enter the Warped Forest in the Nether, I've noticed a few items affiliated with plants is missing in Creative mode.

It says: 
The game crashed whilst exception while ticking
Error: java.lang.StackOverflowError: Exception while ticking
Exit Code: -1

Here's the entire log: https://pastebin.com/HfZj8qXf

**Comment by augustresende** [comment]
Fixed.
