### ISSUE TITLE
1.16.4 Problem (Bug)

### ISSUE THREAD

**Issue by Gomez96** [AugustoResende/VanillaExperience#4]
The newest version of your mod: **vanillaexperience-1.16.3-0.2.5** doesn't work in 1.16.4 and makes the launcher crash. 

Here's the log: **https://pastebin.com/QvXxHFjG**

**Comment by augustresende** [comment]
This is not caused by my mod. mixins.mm.json is from modmuss50 mods, probably from OptiFabric or mm@2.1 mod.
